import { useEffect, useState } from 'react';
import { AdminInboxItem, AdminProfessional, AdminSpecialty, AdminEps, AdminPlan, createAdminEps, createAdminPlan, createAdminProfessional, createAdminSpecialty, decideAdminAppointment, decideAdminReschedule, getAdminEps, getAdminInbox, getAdminPlans, getAdminProfessionals, getAdminSpecialties, assignProfessionalLocations, assignProfessionalSpecialties } from '../lib/api';

export function AdminScreen({ accessToken, onLogout }: { accessToken: string; onLogout: () => void }) {
  const [items,setItems]=useState<AdminInboxItem[]>([]),[specialties,setSpecialties]=useState<AdminSpecialty[]>([]),[eps,setEps]=useState<AdminEps[]>([]),[plans,setPlans]=useState<AdminPlan[]>([]),[professionals,setProfessionals]=useState<AdminProfessional[]>([]),[message,setMessage]=useState('');
  const [code,setCode]=useState(''),[name,setName]=useState(''),[epsId,setEpsId]=useState(''),[professionalEmail,setProfessionalEmail]=useState(''),[professionalCode,setProfessionalCode]=useState(''),[professionalPassword,setProfessionalPassword]=useState('');
  const [from,setFrom]=useState(''),[to,setTo]=useState(''),[filterLocation,setFilterLocation]=useState(''),[filterProfessional,setFilterProfessional]=useState(''),[filterSpecialty,setFilterSpecialty]=useState('');
  const [selectedProfessional,setSelectedProfessional]=useState(''),[assignedSpecialties,setAssignedSpecialties]=useState(''),[assignedLocations,setAssignedLocations]=useState('');
  const loadCatalogs=()=>Promise.all([getAdminSpecialties(accessToken),getAdminEps(accessToken),getAdminProfessionals(accessToken)]).then(([s,e,p])=>{setSpecialties(s);setEps(e);setProfessionals(p);});
  const loadInbox=()=>getAdminInbox(accessToken,{from:from||undefined,to:to||undefined,locationId:filterLocation?Number(filterLocation):undefined,professionalId:filterProfessional?Number(filterProfessional):undefined,specialtyId:filterSpecialty?Number(filterSpecialty):undefined}).then(i=>setItems(i.items));
  const load=()=>Promise.all([loadInbox(),loadCatalogs()]);
  useEffect(()=>{load().catch(()=>setMessage('No fue posible cargar la administración.'));},[]);
  async function decide(i:AdminInboxItem,approve:boolean){const reason=approve?undefined:window.prompt('Motivo del rechazo')??undefined;if(!approve&&!reason)return;try{if(i.type==='RESCHEDULE')await decideAdminReschedule(i.id,approve,reason,accessToken);else await decideAdminAppointment(i.id,approve,reason,accessToken);setMessage('Decisión aplicada.');await loadInbox();}catch{setMessage('No fue posible aplicar la decisión.');}}
  async function addSpecialty(){try{await createAdminSpecialty({code,name,duration:30,general:false,requiresAdminApproval:true},accessToken);setCode('');setName('');setMessage('Especialidad creada.');await loadCatalogs();}catch{setMessage('No fue posible crear la especialidad.');}}
  async function addEps(){try{await createAdminEps({code,name},accessToken);setCode('');setName('');setMessage('EPS creada.');await loadCatalogs();}catch{setMessage('No fue posible crear la EPS.');}}
  async function addPlan(){try{await createAdminPlan({epsId:Number(epsId),regimeId:1,code,name},accessToken);setMessage('Plan creado.');if(epsId)setPlans(await getAdminPlans(Number(epsId),accessToken));}catch{setMessage('No fue posible crear el plan.');}}
  async function addProfessional(){try{await createAdminProfessional({firstName:'Profesional',lastName:'Nuevo',documentType:'CC',documentNumber:Date.now().toString(),email:professionalEmail,phone:'',password:professionalPassword,professionalCode,licenseNumber:professionalCode},accessToken);setProfessionalPassword('');setMessage('Profesional creado.');await loadCatalogs();}catch{setMessage('No fue posible crear el profesional.');}}
  async function assign(){if(!selectedProfessional)return;try{const specs=assignedSpecialties.split(',').map(Number).filter(Boolean).map((specialtyId,index)=>({specialtyId,primary:index===0}));const locations=assignedLocations.split(',').map(Number).filter(Boolean);await assignProfessionalSpecialties(Number(selectedProfessional),specs,accessToken);await assignProfessionalLocations(Number(selectedProfessional),locations,accessToken);setMessage('Asignaciones actualizadas.');}catch{setMessage('No fue posible actualizar las asignaciones.');}}
  return <main className="w-full max-w-5xl rounded-3xl bg-white p-8 shadow-xl"><header className="flex justify-between"><div><h1 className="text-2xl font-bold text-slate-900">Administración</h1><p className="text-sm text-slate-500">Bandeja, catálogos y profesionales.</p></div><button onClick={onLogout} className="text-sm text-blue-600">Cerrar sesión</button></header>{message&&<p className="mt-4 text-sm text-emerald-700">{message}</p>}
    <section className="mt-6 space-y-3"><h2 className="font-semibold">Solicitudes pendientes</h2><div className="grid gap-2 sm:grid-cols-5"><input className="rounded-xl border p-2" type="date" value={from} onChange={e=>setFrom(e.target.value)} aria-label="Desde"/><input className="rounded-xl border p-2" type="date" value={to} onChange={e=>setTo(e.target.value)} aria-label="Hasta"/><input className="rounded-xl border p-2" type="number" value={filterLocation} onChange={e=>setFilterLocation(e.target.value)} placeholder="ID sede"/><input className="rounded-xl border p-2" type="number" value={filterProfessional} onChange={e=>setFilterProfessional(e.target.value)} placeholder="ID profesional"/><input className="rounded-xl border p-2" type="number" value={filterSpecialty} onChange={e=>setFilterSpecialty(e.target.value)} placeholder="ID especialidad"/></div><button className="rounded-xl border px-3 py-2" onClick={()=>loadInbox().catch(()=>setMessage('No fue posible aplicar los filtros.'))} type="button">Aplicar filtros</button>{items.length===0?<p className="text-sm text-slate-500">No hay solicitudes pendientes.</p>:items.map(i=><article className="rounded-xl border p-4" key={`${i.type}-${i.id}`}><div className="flex flex-wrap justify-between gap-3"><div><p className="font-semibold">{i.type} · {i.specialty}</p><p className="text-sm text-slate-500">{i.startAt.replace('T',' ')} · {i.location}</p></div><div className="flex gap-3"><button className="text-emerald-700" onClick={()=>decide(i,true)} type="button">Aprobar</button><button className="text-rose-700" onClick={()=>decide(i,false)} type="button">Rechazar</button></div></div></article>)}</section>
    <section className="mt-8 border-t pt-6"><h2 className="font-semibold">Crear catálogo</h2><div className="mt-3 grid gap-2 sm:grid-cols-3"><input className="rounded-xl border p-2" value={code} onChange={e=>setCode(e.target.value)} placeholder="Código"/><input className="rounded-xl border p-2" value={name} onChange={e=>setName(e.target.value)} placeholder="Nombre"/><button className="rounded-xl bg-blue-600 px-3 py-2 text-white" onClick={addSpecialty} type="button">Crear especialidad</button><button className="rounded-xl bg-indigo-600 px-3 py-2 text-white" onClick={addEps} type="button">Crear EPS</button></div><div className="mt-4 flex gap-2"><select className="rounded-xl border p-2" value={epsId} onChange={e=>{setEpsId(e.target.value);setPlans([]);}}><option value="">Selecciona EPS</option>{eps.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select><button className="rounded-xl border px-3" onClick={()=>epsId&&getAdminPlans(Number(epsId),accessToken).then(setPlans)} type="button">Cargar planes</button><button className="rounded-xl bg-slate-800 px-3 py-2 text-white" onClick={addPlan} type="button">Crear plan</button></div><div className="mt-3 grid gap-2 sm:grid-cols-3">{specialties.map(s=><span className="rounded-lg bg-slate-50 p-2 text-xs" key={s.id}>{s.id} · {s.name}</span>)}{plans.map(p=><span className="rounded-lg bg-amber-50 p-2 text-xs" key={p.id}>{p.name}</span>)}</div></section>
    <section className="mt-8 border-t pt-6"><h2 className="font-semibold">Crear profesional</h2><div className="mt-3 flex flex-wrap gap-2"><input className="rounded-xl border p-2" value={professionalEmail} onChange={e=>setProfessionalEmail(e.target.value)} placeholder="Correo"/><input className="rounded-xl border p-2" value={professionalCode} onChange={e=>setProfessionalCode(e.target.value)} placeholder="Código profesional"/><input className="rounded-xl border p-2" type="password" minLength={8} value={professionalPassword} onChange={e=>setProfessionalPassword(e.target.value)} placeholder="Contraseña temporal"/><button className="rounded-xl bg-violet-600 px-3 py-2 text-white" onClick={addProfessional} type="button">Crear</button></div><div className="mt-3 space-y-2">{professionals.map(p=><div className="rounded-lg border p-2 text-sm" key={p.id}>{p.id} · {p.firstName} {p.lastName} · {p.email} · {p.professionalCode}</div>)}</div><div className="mt-4 grid gap-2 sm:grid-cols-3"><select className="rounded-xl border p-2" value={selectedProfessional} onChange={e=>setSelectedProfessional(e.target.value)}><option value="">Profesional a asignar</option>{professionals.map(p=><option key={p.id} value={p.id}>{p.id} · {p.email}</option>)}</select><input className="rounded-xl border p-2" value={assignedSpecialties} onChange={e=>setAssignedSpecialties(e.target.value)} placeholder="IDs especialidades: 1,2"/><input className="rounded-xl border p-2" value={assignedLocations} onChange={e=>setAssignedLocations(e.target.value)} placeholder="IDs sedes: 1,2"/><button className="rounded-xl border px-3 py-2" onClick={assign} type="button">Guardar asignaciones</button></div></section>
  </main>;
}
