import { FormEvent, useEffect, useState } from 'react';
import { getProfile, updateProfile, type Profile } from '../lib/api';
export function ProfilePanel({ accessToken }: { accessToken: string }) {
  const [profile, setProfile] = useState<Profile | null>(null); const [firstName, setFirstName] = useState(''); const [lastName, setLastName] = useState(''); const [phone, setPhone] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  useEffect(() => { getProfile(accessToken).then((value) => { setProfile(value); setFirstName(value.firstName); setLastName(value.lastName); setPhone(value.phone ?? ''); }).catch(() => setError('No fue posible cargar el perfil.')); }, [accessToken]);
  async function save(event: FormEvent) { event.preventDefault(); setError(''); try { setProfile(await updateProfile({ firstName, lastName, phone: phone || null }, accessToken)); setMessage('Perfil actualizado.'); } catch { setError('No fue posible actualizar el perfil.'); } }
  if (!profile) return <section className="rounded-2xl border border-slate-200 bg-white p-5 text-sm text-slate-500">{error || 'Cargando perfil…'}</section>;
  return <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-semibold text-slate-900">Mi perfil</h2><p className="mt-1 text-xs text-slate-500">{profile.email} · {profile.documentType} {profile.documentNumber}</p><form onSubmit={save} className="mt-4 grid gap-3 sm:grid-cols-3"><input className="rounded-xl border border-slate-200 px-3 py-2" value={firstName} onChange={(event) => setFirstName(event.target.value)} required placeholder="Nombres" /><input className="rounded-xl border border-slate-200 px-3 py-2" value={lastName} onChange={(event) => setLastName(event.target.value)} required placeholder="Apellidos" /><input className="rounded-xl border border-slate-200 px-3 py-2" value={phone} onChange={(event) => setPhone(event.target.value)} placeholder="Teléfono" /><button className="rounded-xl bg-blue-600 px-4 py-2 text-sm font-medium text-white sm:col-span-3 sm:w-fit" type="submit">Guardar cambios</button></form>{message && <p className="mt-3 text-sm text-emerald-700">{message}</p>}{error && <p className="mt-3 text-sm text-rose-700">{error}</p>}</section>;
}
